FROM bizhost/ubuntu20.04_nginx

LABEL maintainer="bizhost"

ENV DEBIAN_FRONTEND noninteractive
ENV T_HOSTNAME nginx

ARG FORWARD_PHP_PORT
ARG APP_NAME
ARG USERNAME="${APP_NAME}"
ARG USER_UID
ARG USER_GID=$USER_UID

# 사용자 추가
RUN groupadd --gid $USER_GID $USERNAME
RUN useradd --shell /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
RUN chmod 0440 /etc/sudoers.d/$USERNAME

USER root
COPY ./.bash_aliases /home/$USERNAME/.bash_aliases
RUN chown $USERNAME:$USERNAME /home/$USERNAME/.bash_aliases
COPY ./.bash_aliases /root/.bash_aliases

WORKDIR /root/

CMD ["bash"]

ENTRYPOINT ["start-container", "bash"]
